name: cards_of_conscience
description: "A simulation card game for policymaking."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^14.8.1
  uuid: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  showcaseview: ^4.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/data/
