name: cards_of_conscience
description: "A simulation card game for policymaking."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^14.8.1
  uuid: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  showcaseview: ^4.0.1
  google_fonts: ^6.1.0
  # Added for Phase 2
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  just_audio: ^0.9.36
  flutter_sound: ^9.2.13
  permission_handler: ^11.1.0 
  flutter_animate: ^4.5.0
  introduction_screen: ^3.1.12
  chat_bubbles: ^1.5.0
  flutter_markdown: ^0.6.18
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  analytics_event: ^1.2.1
  fl_chart: ^0.71.0
  flutter_gemini: ^3.0.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/audio/
    - assets/images/
    - assets/images/scenarios/
